language: c

matrix:
  include:
    - os: linux
      compiler: clang
      env: EXTRA_FLAGS="-DCLANG_ADDRESS_SANITIZER=ON"
    - os: linux
      compiler: gcc-5
      env: GCOV=gcov-5 EXTRA_FLAGS="-DUSE_COVERAGE=ON"

before_install:
  # cmocka
  - wget https://cmocka.org/files/1.1/cmocka-1.1.0.tar.xz
  - tar -xJvf cmocka-1.1.0.tar.xz
  - cd cmocka-1.1.0 && mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make -j2 && sudo make install
  - cd ../..
  - rm -rf cmocka-1.1.0
  # libuv
  - curl -L https://github.com/libuv/libuv/archive/v1.10.0.tar.gz | tar xzf -
  - (cd libuv-1.10.0 && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install)
  - rm -rf libuv-1.10.0
  # msgpack-c
  - curl -L https://github.com/msgpack/msgpack-c/archive/cpp-2.0.0.tar.gz | tar xzf -
  - (cd msgpack-c-cpp-2.0.0 && cmake . && make && sudo make install)
  - rm -rf msgpack-c-cpp-2.0.0
  # coveralls
  - pip install --user cpp-coveralls

addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
    packages:
      - autoconf
      - automake
      - build-essential
      - clang-3.4
      - cmake
      - g++-5-multilib
      - g++-multilib
      - gcc-5-multilib
      - gcc-multilib
      - gdb
      - libc6-dev-i386
      - libtool
      - llvm-3.4-dev
      - ninja-build
      - pkg-config
      - libbsd-dev
      - libhiredis-dev

before_script: redis-server redis-test.conf
script: make sb && make test && make sb-makekey && ./out/bin/sb-makekey && ./out/bin/sb-test
after_success: .ci/after_success.sh
