sudo: false
language: c

matrix:
  include:
    - os: linux
      compiler: clang-3.6
      env: GCOV=llvm-cov-3.6 EXTRA_FLAGS="-DUSE_GCOV=ON"

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
    packages:
      - autoconf
      - automake
      - build-essential
      - clang-3.6
      - cmake
      - g++-5-multilib
      - g++-multilib
      - gcc-5-multilib
      - gcc-multilib
      - gdb
      - libc6-dev-i386
      - libtool
      - llvm-3.6-dev
      - ninja-build
      - pkg-config
  
script: make sb && make test
