language: c

matrix:
  include:
    - os: linux
      compiler: clang-3.6
      env: GCOV=llvm-cov-3.6 EXTRA_FLAGS="-DUSE_COVERAGE=ON"

before_install:
  # libsodium
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get update -q
  - sudo apt-get install -y libsodium-dev
  # cmocka
  - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
  - tar -xJvf cmocka-1.0.1.tar.xz
  - cd cmocka-1.0.1 && mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr .. && make -j2 && sudo make install
  - cd ../..
  - rm -rf cmocka-1.0.1
  # libuv
  - curl -L https://github.com/libuv/libuv/archive/v1.8.0.tar.gz | tar xzf -
  - (cd libuv-1.8.0 && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install)
  - rm -rf libuv-1.8.0
  # msgpack-c
  - curl -L https://github.com/msgpack/msgpack-c/archive/cpp-1.4.0.tar.gz | tar xzf -
  - (cd msgpack-c-cpp-1.4.0 && ./bootstrap && ./configure --prefix=/usr && make && sudo make install)
  - rm -rf msgpack-c-cpp-1.4.0
  # coveralls
  - pip install --user cpp-coveralls

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - autoconf
      - automake
      - build-essential
      - clang-3.6
      - cmake
      - g++-5-multilib
      - g++-multilib
      - gcc-5-multilib
      - gcc-multilib
      - gdb
      - libc6-dev-i386
      - libtool
      - llvm-3.6-dev
      - ninja-build
      - pkg-config
      - libbsd-dev
      - libhiredis-dev
  
before_script: redis-server redis-test.conf
script: make sb && make test && ./out/bin/sb-test
after_success: coveralls --exclude test --gcov "$(which "${GCOV}")" --encoding iso-8859-1 || echo 'coveralls upload failed.'
