sudo: false
language: c

matrix:
  include:
    - os: linux
      compiler: clang-3.6
      env: GCOV=llvm-cov-3.6 EXTRA_FLAGS="-DUSE_GCOV=ON"

before_install:
  - sudo apt-get -qq update
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get install -y libuv-dev libmsgpack-dev hiredis libbsd-dev libsodium-dev

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - autoconf
      - automake
      - build-essential
      - clang-3.6
      - cmake
      - g++-5-multilib
      - g++-multilib
      - gcc-5-multilib
      - gcc-multilib
      - gdb
      - libc6-dev-i386
      - libtool
      - llvm-3.6-dev
      - ninja-build
      - pkg-config
  
script: make sb && make test
