language: c

matrix:
  include:
    - os: linux
      compiler: clang
      env: EXTRA_FLAGS="-DCLANG_ADDRESS_SANITIZER=ON"
    - os: linux
      compiler: gcc-5
      env: GCOV=gcov-5 EXTRA_FLAGS="-DUSE_COVERAGE=ON"

addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
    packages:
      - autoconf
      - automake
      - build-essential
      - clang-3.4
      - cmake
      - g++-5-multilib
      - g++-multilib
      - gcc-5-multilib
      - gcc-multilib
      - gdb
      - libc6-dev-i386
      - libtool
      - llvm-3.4-dev
      - ninja-build
      - pkg-config
      - python3.3-dev
      - libbsd-dev
      - libhiredis-dev

before_install: .ci/before_install.sh
before_script: redis-server redis-test.conf
script: make sb && make test && make sb-makekey && ./build/bin/sb-makekey && ./build/bin/sb-test
after_success: .ci/after_success.sh
